from . import bugun_namaz_callback
from . import obuna_namaz_callback
from . import regions_namaz_callback
from . import quran_callback
from . import send_suralar_callback
from . import turlari_namaz_callback
from . import guslvatahorat_callback
from . import send_namaz_callback
from . import asmaul_husna_callback
from . import zikr_callback
from . import duo_callback
from . import salovat_callback
from . import kitoblar_callback
from . import manolar_callback
from . import sahobalar_callback
from . import zam_suralar_callback
from . import sendFilms
from . import Qurantartili
from . import send_arab_tili