from . import asmaul_husna_Inline
from . import duo_inline
from . import kitoblar_Inline
from . import namozturlar_Inline
from . import obuna_Inline
from . import quran_Inline
from . import regions_Inline
from . import sahobalar_inline
from . import zam_sura_inline
from . import kino
from . import dars
from . import arab_tili
